id = "cpp"
name = "C++"
extensions = ["cc", "cpp", "cxx", "c++", "hpp", "hh", "hxx", "h++"]
comment_nodes = ["comment"]

[[scopes]]
kind = "class_specifier"
field = "name"

[[scopes]]
kind = "struct_specifier"
field = "name"

[[scopes]]
kind = "namespace_definition"
field = "name"
